repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: ruff format
        entry: ruff format
        language: python
        types: [python]
        stages: [commit]
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix
        language: python
        types: [python]
        stages: [commit]
